### ISSUE TITLE
SyndicatePanel

### ISSUE THREAD

**Issue by snowhawk04** [IlliumIv/BroodyHen#1]
It seems SyndicatePanel and the InventoryPanel cannot both appear at the same time. Should the check exist? It almost seems like it should always draw if the InventoryPanel is showing, whether the atlas or skill tree is visible. 

https://github.com/IlliumIv/BroodyHen/blob/9a6d40bf2e29c081bfc4f05df624dcf0f2a31f67/Main/Core.cs#L87

Should this instead check `_inventories.Children[3].IsVisible` so it hides when the cosmetic tab is visible?

**Comment by IlliumIv** [comment]
Hi

Ty, i'll rewrite checks.
